name: filebeat

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/syslog-ng/syslog.log
    fields:
      log_type: syslog
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /var/log/syslog-ng/auth.log
    fields:
      log_type: auth
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /var/log/syslog-ng/ssh.log
    fields:
      log_type: ssh
    fields_under_root: true
    
  - type: log
    enabled: true
    paths:
      - /var/log/syslog-ng/kernel.log
    fields:
      log_type: kernel
    fields_under_root: true
    
  - type: log
    enabled: true
    paths:
      - /var/log/syslog-ng/daemon.log
    fields:
      log_type: daemon
    fields_under_root: true
    
  - type: log
    enabled: true
    paths:
      - /var/log/syslog-ng/local.log
    fields:
      log_type: local
    fields_under_root: true
    
  - type: log
    enabled: true
    paths:
      - /var/log/syslog-ng/auditd.log
    fields:
      log_type: auditd
    fields_under_root: true

processors:
  - add_cloud_metadata: ~

output.logstash:
  hosts: [ "logstash:5044" ]
  ssl.enabled: false